version: '3.3'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db:db
    networks:
      - postgres-compose-network

  db:
    image: postgres
    environment:
      - POSTGRES_DB= postgres
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
    
      
      
    ports:
      - "7777:5432"
    volumes:
      - /home/duducp/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge